# Generated by Django 4.2.6 on 2025-07-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('unidade_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EscalaPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_id', models.IntegerField()),
                ('semana_inicio', models.DateField()),
                ('semana_fim', models.DateField()),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantao.plantao')),
            ],
        ),
    ]
