# Generated by Django 4.2.6 on 2025-07-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('unidade_id', models.IntegerField()),
                ('atividade_id', models.IntegerField()),
                ('veiculo_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
