# Generated by Django 4.2.6 on 2025-07-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_programacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='programacoes',
            table='programacoes',
        ),
    ]
